### ISSUE TITLE
Notification icon problem

### ISSUE THREAD

**Issue by nachete1987** [mirovit/nova-notifications#1]
I follow readme instructions but notification icon is not place correctly. Thanks
![error_user_partial](https://user-images.githubusercontent.com/14239923/78435932-c44fbd00-7676-11ea-9d95-3369f183ac39.png)
![code](https://user-images.githubusercontent.com/14239923/78435943-c4e85380-7676-11ea-9c27-c8691bf17f8b.png)

**Comment by mirovit** [comment]
Hi @nachete1987,

Yes, you need to do a bit of changes to your layout file for it to display next to the user item.

First, include the partial nova-notifications::dropdown in the layout.blade.php.

It should be before or after:
```
@inclide('nova-notifications::dropdown')
<dropdown class="ml-8 h-9 flex items-center dropdown-right">
    @include('nova::partials.user')
</dropdown>
```
Then wrap both dropdowns with:
```
<div class="flex flex-1 align-content-end justify-end">
    @inclide('nova-notifications::dropdown')
    <dropdown class="ml-8 h-9 flex items-center dropdown-right">
        @include('nova::partials.user')
    </dropdown>
</div>
```

There are two more elements before them - an <a> tag and the global search, wrap them in:
```
<div class="flex flex-1 items-center">
...
</div>
```

Finally, add this class to the div that holds them: `justify-between`

<img width="1011" alt="Screenshot 2020-04-04 at 15 21 47" src="https://user-images.githubusercontent.com/909813/78450616-9a06fb00-7688-11ea-8eef-e1403a756771.png">

**Comment by nachete1987** [comment]
Thanks!! now it works! only one think, in dropdown section, you must change <dropdown class="ml-auto h-9 flex items-center dropdown-right"> to <dropdown class="ml-8 h-9 flex items-center dropdown-right">

``<div class="flex flex-1 align-content-end justify-end">
                        @include('nova-notifications::dropdown')
                        
                        <dropdown class="ml-8 h-9 flex items-center dropdown-right">
                            @include('nova::partials.user')
                        </dropdown>
                    </div>``

**Comment by issour** [comment]
When Apply Responsive the  @include('nova-notifications::dropdown') disappear !
I use cloudcake/nova-fixed-bars for responsive
thx !
