### ISSUE TITLE
Notification is not realtime, it needs to refresh the page.

### ISSUE THREAD

**Issue by MdMostaFizurRahaman** [mirovit/nova-notifications#10]
Notification is not realtime, it needs to refresh the page.

**Comment by mirovit** [comment]
Hello @MdMostaFizurRahaman,

Can you provide more information about your issue? I can only assume that you have not setup Laravel Echo as described in the README file of the package. You need to setup some sort of WebSocket connection, either Socket.IO or a service like Pusher to achieve the real time notifications. If you do not see your notifications, the only conclusion I get draw is that you haven't setup that or it is setup incorrectly.

Please verify that you have the proper [Broadcasting](https://laravel.com/docs/7.x/broadcasting#introduction) and [Echo](https://laravel.com/docs/7.x/broadcasting#installing-laravel-echo) installations.

**Comment by phlisg** [comment]
For people landing here like me when experiencing the same issue, don't forget to run `php artisan queue:work` and then everything should be good :)

Thank you for the great package!

**Comment by mirovit** [comment]
> For people landing here like me when experiencing the same issue, don't forget to run `php artisan queue:work` and then everything should be good :)
> 
> Thank you for the great package!

Thank you @phlisg. The running of the queues is only required if you implement the `ShouldQueue` interface, otherwise, they should be sent out without any delay.
