### ISSUE TITLE
Visualization problem when not in fullscreens mode

### ISSUE THREAD

**Issue by nachete1987** [mirovit/nova-notifications#11]
When the screen is small, Nova notification icon disappear. It's a problem mainly in mobile.

Thanks a lot!!!!

**Comment by nachete1987** [comment]
Hi @mirovit something new? Thanks a lot!! Your tool is very useful to me

**Comment by mirovit** [comment]
That seems to be an issue with styling, since the icon is just a sample implementation, you can tweak it to fit your screen. Also, are you using the built in theme or another one?

**Comment by nachete1987** [comment]
It happens with build in theme and with gregoriohc/laravel-nova-theme-responsive

**Comment by phuclh** [comment]
I have the same problem, the icon doesn't show. I already included the notification dropdown view in the layout file.

```
                    @include('nova-notifications::dropdown')

                    <dropdown class="ml-auto h-9 flex items-center dropdown-right">
                        @include('nova::partials.user')
                    </dropdown>
```

<img width="564" alt="Screen Shot 2020-06-01 at 11 00 48 PM" src="https://user-images.githubusercontent.com/6707194/83485370-bee6d700-a45b-11ea-938d-a62257598f1f.png">

**Comment by nachete1987** [comment]
Any news? Thanks

**Comment by mirovit** [comment]
I haven't had time to debug it. It seems like it is a front end issue, which can be fixed from your code, since I have only provided a sample of how to put the notification icon in place.

**Comment by MdMostaFizurRahaman** [comment]
if your are using "gregoriohc/laravel-nova-theme-responsive" package, this issue is causing for those css
  

> .h-header .dropdown-trigger span, .h-header .dropdown-trigger svg {
>         display: none;
>    }

So, make an custom theme for nova and overrider those css like

  **.h-header .dropdown-trigger span, .h-header .dropdown-trigger svg {
        display: block;
    }**
