### ISSUE TITLE
Uncaught (in promise) ReferenceError: Echo is not defined

### ISSUE THREAD

**Issue by thaifani** [mirovit/nova-notifications#12]
just get this in console 
```
notifications:1 Uncaught (in promise) ReferenceError: Echo is not defined
    at notifications:1
    at notifications:1
```

**Comment by mirovit** [comment]
Please refer to this issue, which was closed. You do not have the correct setup in your project.

https://github.com/mirovit/nova-notifications/issues/3

**Comment by thaifani** [comment]
i did the setup as you explained in setup phases put i get this error

**Comment by thaifani** [comment]
Ok  I will try and see what i see
