### ISSUE TITLE
The bell is in the middle of header

### ISSUE THREAD

**Issue by xoco70** [mirovit/nova-notifications#13]
Hi,

I use Laravel 7, Nova 3.8.1, and theme gregoriohc/laravel-nova-theme-responsive

When including the bell, I see it here;

![Screenshot from 2020-07-31 08-59-50](https://user-images.githubusercontent.com/5855577/89009185-4d68bf00-d30c-11ea-8615-1d88158ebfec.png)

the code:

```
@include('nova-notifications::dropdown')
                    <dropdown class="ml-auto h-9 flex items-center dropdown-right">
                        @include('nova::partials.user')
                    </dropdown>
```

**Comment by xoco70** [comment]
Was my bad, sorry !

**Comment by internetbug256** [comment]
Hello. I am having some issues too to locate the best place for the bell & popup. Does anyone know the ideal location? No matter where I put it, it never shows properly and it bothers the other dropdown trigger event
![trigger](https://user-images.githubusercontent.com/50501948/145622916-ec8e74bc-bdd3-46d5-bcbe-931feca7cda7.png)
s
