### ISSUE TITLE
Missing release updates

### ISSUE THREAD

**Issue by nbayramberdiyev** [mirovit/nova-notifications#17]
- Laravel Version: 8.9.0
- Laravel Nova Version: 3.10.0
- PHP Version: 7.4.10

### Description:

Looks like you haven't released the latest version yet since I'm not able to use [`icon`](https://github.com/mirovit/nova-notifications/blob/master/src/Notification.php#L126), [`showMarkAsRead`](https://github.com/mirovit/nova-notifications/blob/master/src/Notification.php#L132) and [`showCancel`](https://github.com/mirovit/nova-notifications/blob/master/src/Notification.php#L138) methods. Also downloaded [the latest release](https://github.com/mirovit/nova-notifications/archive/1.0.4.zip) manually, but still wasn't able to see these methods.

**Comment by mirovit** [comment]
@nbayramberdiyev I have just published another release. Make sure that the package dependency in you composer.json file is not locked to a specific version. The current version is 1.0.5 and includes all changes present in master branch.
