### ISSUE TITLE
[Feature Request] Add ability to override controllers

### ISSUE THREAD

**Issue by vesper8** [mirovit/nova-notifications#18]
I would like to see the ability to specify my own controllers for retrieving unread notifications and making them as read. The reason is that my users that use the nova dashboard also receiving notifications as part of my web app and right now the nova dashboard is retrieving ALL notifications including those not meant for the nova dashboard. So I would like to modify the query so that it only handles notifications that are specifically marked as being for nova

**Comment by mirovit** [comment]
@vesper8 I have just published a new release - 1.0.5 that introduces options to the config file for overriding of controllers.

**Comment by vesper8** [comment]
sweet! thank you!
