### ISSUE TITLE
problem with nova-echo and nova-notifications

### ISSUE THREAD

**Issue by nachete1987** [mirovit/nova-notifications#2]
I have installed nova-echo package to integrate with pusher and I obtain an error
When I remove ` @include('nova-notifications::dropdown')` I connect OK with pusher 
![pusher](https://user-images.githubusercontent.com/14239923/78464519-d79c7000-76ea-11ea-8fe0-7611060db3f7.png)
But when I include the line, I obtain an auth error in console
![error_pusher1](https://user-images.githubusercontent.com/14239923/78464526-e8e57c80-76ea-11ea-960d-d47623fd5f33.png)

Could you review it

Thanks!
If you need more info, I will provide you

**Comment by mirovit** [comment]
It seems like you have not setup the broadcasting correctly.

First, ensure you have a `channels.php` file in the `routes` directory. Then if you have it, see if you have the authorization set correctly:
```php
Broadcast::channel('App.Models.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});
```

If your User model is in the App\Models namespace, then it should be as my example, but if you're using the default models structure under the App namespace, then it should be `App.User.{id}'` and in this case there is one more step to take - export the config file from the package and update the namespace there to reflect this:
```php
<?php

return [
    // The Echo namespaced path to the User model
    'user_model' => 'App.User',
];
```

Let me know if you need more assistance.

**Comment by nachete1987** [comment]
Thanks @mirovit ! the problem was te Echo namespaced in nova-notification.php config file.
My user model is under App and by default, in config file, App.Model.User is indicated.
Many hours yesterday and was only a value in config file, thanks again!!
