### ISSUE TITLE
Notification diffForHumans translated

### ISSUE THREAD

**Issue by newtongamajr** [mirovit/nova-notifications#23]
Hi @mirovit,

First of all, thank's for your great and amazing package! 

I'd like to suggest that when presenting the diff for humans from the created_at, to use Laravel Locale configured. This way users should read this in their native language!

Best regards!
![Captura de tela 2021-01-28 150339](https://user-images.githubusercontent.com/8673343/106179702-2a637e80-617a-11eb-8a51-dbe7881f941b.png)

**Comment by mirovit** [comment]
Hi @newtongamajr,

Thank you for the feedback. This actually has been brought up before - I don't think that the package should be responsible for setting the application locale, it should be done on app level. I think this is something that needs to be added to the README file.

Here's the solution - https://github.com/mirovit/nova-notifications/issues/5#issuecomment-616490916

Hope this helps you! Let me know if you need more information.
