### ISSUE TITLE
dark background behind the bell icon.. why?

### ISSUE THREAD

**Issue by vesper8** [mirovit/nova-notifications#27]
I noticed that you add the class `bg-gray-800` to the bell svg

This creates an ugly dark background behind the bell

![Screen Shot 2021-05-10 at 6 45 37 PM](https://user-images.githubusercontent.com/816028/117733660-a1d58f00-b1fa-11eb-8324-58a7c516e89c.png)

Just wondering why this dark bg is there in the first place

And is there an easy way to modify the classes ?

As you can see the badge is also mis-aligned

**Comment by vesper8** [comment]
Was able to hack it up by changing this:

```
                    <div class="ml-auto flex flex-row items-center">
                        <div id="nova-notifications">
                            @include('nova-notifications::dropdown')
                        </div>

                        <dropdown class="pl-4 h-9 flex items-center dropdown-right">
                            @include('nova::partials.user')
                        </dropdown>
                    </div>
```

and then in my custom theme:

```
#nova-notifications > div > div > button > div > span > svg {
  background-color: transparent !important;
}

#nova-notifications > div > div > button > div > span > span {
  right: -14px !important;
  top: 10px !important;
}
```

**Comment by mirovit** [comment]
Hello @vesper8,

This issue has been resolved thanks to @AliSaleem27, I've created a new version and you can update you dependency of this package.
