### ISSUE TITLE
Problem with sync notification only show after refresh

### ISSUE THREAD

**Issue by issour** [mirovit/nova-notifications#3]
in console : 

WebSocket connection to 'wss://laravel.test:6001/app/100300100300?protocol=7&client=js&version=4.3.1&flash=false' failed: WebSocket is closed before the connection is established.
I use Valet, Laravel Websockets with pusher and nova-echo (from : coreproc/nova-echo)
thx !

**Comment by mirovit** [comment]
It seems like there is an issue with your WebSocket server configuration. This is not related to the way this package works. As long as you have Laravel's broadcasting working, the package will work as well.

Can you verify that you WS server is working and you can connect to it?

Since notifications are stored in the database, this is why you see them reflected in the header on refresh.

**Comment by issour** [comment]
Thx for your replay :)
Can you share your config ?
what you use for backend & frontend ?
Many thx

**Comment by mirovit** [comment]
I'm using Pusher with Echo, there is nothing special in my config, I've followed the event broadcasting setup from the Laravel docs - [Broadcasting](https://laravel.com/docs/7.x/broadcasting#driver-prerequisites) and [Echo](https://laravel.com/docs/7.x/broadcasting#installing-laravel-echo).

**Comment by issour** [comment]
Hi @mirovit thx for your sharing !!!!
other question please !
if i add Echo to my Laravel application, it's add too to Nova ?
I switch out nova-echo from : coreproc/nova-echo and i have the flowing error : 
```
notifications:1 Uncaught (in promise) ReferenceError: Echo is not defined
    at notifications:1
    at notifications:1
```
i don't know if this package (coreproc/nova-echo) is the best way to add echo to nova ?
Thx a lot for your help !! 👍

**Comment by mirovit** [comment]
In your Laravel app do the following:

- Intall [Echo](https://laravel.com/docs/7.x/broadcasting#installing-laravel-echo)
- `npm install`
- create an admin.js file in resources/js
```js
import Echo from 'laravel-echo';

// Sample instance with Pusher
window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    encrypted: true
});
```
- add to your webpack.mix.js
```js
mix.js('resources/js/admin.js', 'public/js');
```
- add in your Nova layout.blade.php
```html
// ...
<script src="{{ mix('app.js', 'vendor/nova') }}"></script>
<script src="{{ mix('js/admin.js') }}"></script>
```

**Comment by issour** [comment]
Hi @mirovit It's awesome !!! Thx !!!

**Comment by phuclh** [comment]
> In your Laravel app do the following:
> 
> * Intall [Echo](https://laravel.com/docs/7.x/broadcasting#installing-laravel-echo)
> * `npm install`
> * create an admin.js file in resources/js
> 
> ```js
> import Echo from 'laravel-echo';
> 
> // Sample instance with Pusher
> window.Pusher = require('pusher-js');
> 
> window.Echo = new Echo({
>     broadcaster: 'pusher',
>     key: process.env.MIX_PUSHER_APP_KEY,
>     cluster: process.env.MIX_PUSHER_APP_CLUSTER,
>     encrypted: true
> });
> ```
> 
> * add to your webpack.mix.js
> 
> ```js
> mix.js('resources/js/admin.js', 'public/js');
> ```
> 
> * add in your Nova layout.blade.php
> 
> ```
> // ...
> <script src="{{ mix('app.js', 'vendor/nova') }}"></script>
> <script src="{{ mix('js/admin.js') }}"></script>
> ```

Thank you for the great package. I already had the config like you, but it doesn't show the real-time notification even the Pusher dashboard showed me that there were some messages sent out.

My notification class:
```
    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['database', 'broadcast'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        return (new MailMessage)
                    ->line('The introduction to the notification.')
                    ->action('Notification Action', url('/'))
                    ->line('Thank you for using our application!');
    }

    /**
     * Get the array representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function toArray($notifiable)
    {
        return \Mirovit\NovaNotifications\Notification::make()
            ->info('A new articles was assigned for you.')
            ->subtitle('There is a new user in the system!')
            ->link('/resources/articles')
            ->toArray();
    }
}
```

channel.php (My User Model located at Lar/Tenant/User/Models)
```
Broadcast::channel('Lar.Tenant.User.Models.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});
```

My `admin.js` is the same yours.

**Comment by Pamposgsk** [comment]
> In your Laravel app do the following:
> 
> * Intall [Echo](https://laravel.com/docs/7.x/broadcasting#installing-laravel-echo)
> * `npm install`
> * create an admin.js file in resources/js
> 
> ```js
> import Echo from 'laravel-echo';
> 
> // Sample instance with Pusher
> window.Pusher = require('pusher-js');
> 
> window.Echo = new Echo({
>     broadcaster: 'pusher',
>     key: process.env.MIX_PUSHER_APP_KEY,
>     cluster: process.env.MIX_PUSHER_APP_CLUSTER,
>     encrypted: true
> });
> ```
> 
> * add to your webpack.mix.js
> 
> ```js
> mix.js('resources/js/admin.js', 'public/js');
> ```
> 
> * add in your Nova layout.blade.php
> 
> ```
> // ...
> <script src="{{ mix('app.js', 'vendor/nova') }}"></script>
> <script src="{{ mix('js/admin.js') }}"></script>
> ```

hi 
after following the above i got this error
Unable to locate Mix file: /js/admin.js. (View: C:\MAMP\htdocs\MinoshisCo\resources\views\vendor\nova\layout.blade.php)
Could you please help?

**Comment by mirovit** [comment]
> > In your Laravel app do the following:
> > 
> > * Intall [Echo](https://laravel.com/docs/7.x/broadcasting#installing-laravel-echo)
> > * `npm install`
> > * create an admin.js file in resources/js
> > 
> > ```js
> > import Echo from 'laravel-echo';
> > 
> > // Sample instance with Pusher
> > window.Pusher = require('pusher-js');
> > 
> > window.Echo = new Echo({
> >     broadcaster: 'pusher',
> >     key: process.env.MIX_PUSHER_APP_KEY,
> >     cluster: process.env.MIX_PUSHER_APP_CLUSTER,
> >     encrypted: true
> > });
> > ```
> > 
> > 
> > 
> > * add to your webpack.mix.js
> > 
> > ```js
> > mix.js('resources/js/admin.js', 'public/js');
> > ```
> > 
> > 
> > 
> > * add in your Nova layout.blade.php
> > 
> > ```
> > // ...
> > <script src="{{ mix('app.js', 'vendor/nova') }}"></script>
> > <script src="{{ mix('js/admin.js') }}"></script>
> > ```
> 
> hi
> after following the above i got this error
> Unable to locate Mix file: /js/admin.js. (View: C:\MAMP\htdocs\MinoshisCo\resources\views\vendor\nova\layout.blade.php)
> Could you please help?

@Pamposgsk Did you add the necessary config to you build file? The webpack.mix.js file needs to be updated, so the build would include your new file. Can you post the output of the npm run dev?

**Comment by yahya077** [comment]
Hi, i have `"Invalid key in subscription auth data: 'PUSHER_APP_KEY'"` error. I only get notifications when i refreshed.

My Configuration;
```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: '6ef4y8ax364544fd4188', //this is dummy key don't test it out.
    cluster: 'eu',
    encrypted: true
});
```
I changed key with something wrong key the displaying errors changed to `"App key 6ef4d8ac354444fd4187 not in this cluster. Did you forget to specify the cluster?"`

There is no console error but in the network console pin-pong doesn't look like working. I will add screenshot of messages of network down below (status code: 101)
![Screenshot from 2022-05-19 14-23-32](https://user-images.githubusercontent.com/46659611/169284304-2313e1db-6682-4cb0-b424-f3d25a672ccd.png)
