### ISSUE TITLE
Support route caching

### ISSUE THREAD

**Issue by IMPMAC** [mirovit/nova-notifications#4]
Running the command `php artisan route:cache` returns the following error

> LogicException 
> 
> Unable to prepare route [nova-vendor/nova-notifications/unread] for serialization. Uses Closure.

I imagine it's because you are using a closure and not a controller in the routes file

**Comment by mirovit** [comment]
Yes, you're correct in that assumption. I've pushed a new release with a fix for this, you should be able to run the caching successfully once you update.
