### ISSUE TITLE
translation values

### ISSUE THREAD

**Issue by nachete1987** [mirovit/nova-notifications#5]
Hello @mirovit,

Just to know the times that are handled, without pressing in any way obviously.
Are you working in translation capabilitie?

Thanks a lot!

**Comment by mirovit** [comment]
Hello @nachete1987,

I've just published a new version, which adds the translations. You'll need to publish the package assets with `php artisan vendor:publish` and then you can edit the existing translation or add in any additional language. Also feel free to submit a pull request with your translations in other languages.

The file with translations will be published in `resources/lang/vendor/nova-notifications` and currently there is only the `en.json` file.

**Comment by nachete1987** [comment]
Hi @mirovit 

I have traslated the en.json file generating es.json and all correct except, moment.js functionality to date print.
Could you please include this in tool.js (I think this is the correct place) "moment.locale(process.env.MIX_LANGUAGE_MOMENT);" and in env file I will assign
MIX_LANGUAGE_MOMENT=es

Thanks!

**Comment by mirovit** [comment]
Hi @nachete1987,

This should not be a responsibility of the package. You should set this globally for the app, the way I was able to do it is in the `resources/views/vendor/nova/layout.blade.php`:

Find:
```html
    <!-- Build Nova Instance -->
    <script>
        window.Nova = new CreateNova(config)
    </script>
```

and replace with:
```html
    <!-- Build Nova Instance -->
    <script>
        window.Nova = new CreateNova(config)

        moment.locale('es-es')
    </script>
```

This will set the locale for moment in the whole app. You can pull it from your config instead of hard-coding it, but just as example this should get you sorted.

**Comment by nachete1987** [comment]
Thanks @mirovit I put moment.locale('es') in layout and all correct. I will make a PR as soon as posible when I learn how to do it with es.json
